USE TechStoreDB;

INSERT INTO TechStoreDB.dbo.Categories (Nombre,Descripcion,Imagen) VALUES
	 (N'Telefonos',N'Smartphones de las mejores marcas, con buena cámara, batería y rendimiento para cada presupuesto',N'/images/telefonos.jpg'),
	 (N'Pantallas',N'Monitores y televisores con imagen nítida y colores vivos para trabajar, estudiar o disfrutar tu contenido favorito.',N'/images/pantallas.jpg'),
	 (N'Computacion',N'Laptops, computadoras de escritorio y equipos para estudiar, trabajar y jugar con buen rendimiento.',N'/images/accesorios.jpg');


INSERT INTO TechStoreDB.dbo.Products (Nombre,Descripcion,Precio,Stock,Imagen,CategoriaId,Destacado) VALUES
	 (N'Xiaomi Bundle Note 17 Pro Max 5G 8 GB + 512 GB Negro',N'El Xiaomi Bundle Note 17 Pro Max 5G 8 GB + 512 GB en color negro combina amplia capacidad con funciones pensadas para mantenerte conectado. Su procesador Snapdragon 6 Gen 5 Octa Core de 2.6 GHz, 8 GB de RAM y 512 GB de almacenamiento favorecen la multitarea y el espacio para contenido. Disfruta una pantalla AMOLED de 6.83 pulgadas 1.5K, cámara posterior de 50 MP, frontal de 32 MP y grabación 4K. Completa la experiencia con 5G, NFC, batería de 8340 mAh y resistencia IP68, IP69 e IP69K',699.00,10,N'/images/redmi.jpg',1,1),
	 (N'iPhone 18 Pro 12 GB + 256 GB Black',N'El iPhone 18 Pro 12 GB + 256 GB Black combina una experiencia visual avanzada con capacidad y conectividad para el uso diario. Su pantalla Super Retina XDR OLED de 6.3 pulgadas con resolución 2622 x 1206 píxeles ofrece una visualización detallada, mientras sus 12 GB de RAM y 256 GB de almacenamiento brindan espacio para aplicaciones y contenido. Integra cámara posterior de 48 MP, cámara frontal de 18 MP, USB-C y eSIM. Disfruta un smartphone potente y versátil para acompañar cada momento.',2002.71,10,N'/images/iphone.jpg',1,1),
	 (N'HONOR Choice T10 4GB + 128GB Negro',N'El HONOR Choice T10 4GB + 128GB Negro ofrece una combinación práctica de rendimiento, almacenamiento y conectividad para tus actividades cotidianas. Incorpora procesador MediaTek Helio G81 de hasta 2.0 GHz, 4 GB de RAM, 128 GB de memoria interna y MagicOS 9 basado en Android 15. Su pantalla LCD IPS de 6.75" cuenta con resolución HD de 1604 x 720 píxeles. Integra cámara frontal de 5 MP y cámara posterior de 50 MP + 0.08 MP con flash posterior. Dispone de 4G LTE, Wi-Fi, Bluetooth 5, NFC, USB-C, Dual SIM y lector de huella, además de batería de 5000 mAh. ¡Elige funcionalidad para mantener tu mundo siempre al alcance!',150.08,19,N'/images/honor.jpg',1,0),
	 (N'Pantalla TCL 50" QLED FHD 50S5K',N'La Pantalla TCL 50" QLED FHD 50S5K combina una experiencia visual atractiva con funciones prácticas para disfrutar tus contenidos favoritos en casa. Su pantalla QLED de 50 pulgadas con definición FHD y resolución de 1920 x 1280 píxeles ofrece un formato amplio y diseño plano, acompañado por una tasa de refresco de 60 Hz y compatibilidad HDR10. Integra Google TV como sistema operativo, además de Wi-Fi y Bluetooth integrados para complementar su conectividad. Su acabado en color negro aporta una apariencia moderna que se adapta fácilmente a distintos espacios del hogar. Con medidas de 25.4 cm de alto y 111.1 cm de ancho, y un peso de 10.5 kg, es una opción pensada para renovar tu entretenimiento diario. Disfruta cada momento frente a la pantalla con la propuesta visual y conectada del TCL 50S5K.',299.01,9,N'/images/tlc.jpg',2,1),
	 (N'Pantalla TCL 65" QLED 4K UHD 65T6C',N'Pantalla TCL de 65 pulgadas 4K UHD QLED, modelo 65T6C, una alternativa que combina formato y características confirmadas para disfrutar tus contenidos favoritos con una elección clara y práctica. Su tecnología QLED y definición 4K UHD forman el núcleo de su propuesta de imagen, mientras Google TV funciona como sistema operativo y el WiFi aporta conectividad inalámbrica. Una alternativa TCL para renovar tus momentos frente a la pantalla con características concretas y fáciles de comparar.',589.01,9,N'/images/tlc2.jpg',2,1),
	 (N'Pantalla TCL 65" QD-MiniLed 4K 65C6K',N'Pantalla TCL de 65 pulgadas 4K QD-MiniLed, modelo 65C6K, una propuesta pensada para darle protagonismo a tus momentos de entretenimiento con especificaciones claras y fáciles de identificar. Su tecnología QD-MiniLed y definición 4K forman el núcleo de su propuesta de imagen, mientras Google TV funciona como sistema operativo y el WiFi aporta conectividad inalámbrica. El acabado en color negro completa su presentación y facilita integrarla visualmente en distintos ambientes del hogar. Una TV TCL pensada para acompañar tus contenidos favoritos con una propuesta clara y bien definida.',669.02,8,N'/images/tlc3.jpg',2,0),
	 (N'Laptop HP 15-fd2350la Intel® Core™ Ultra 5 225U 8 GB SSD 512GB 15.6" Plateado natural',N'La Laptop HP D2JV7ABM combina practicidad y capacidad para acompañarte en actividades de estudio, trabajo y uso cotidiano. Incorpora 8 GB de memoria RAM para facilitar la ejecución de tareas habituales y un almacenamiento M.2 de 512 GB que ofrece espacio suficiente para documentos, aplicaciones y archivos importantes. Su pantalla de 15.6 pulgadas brinda un área cómoda de visualización para productividad y entretenimiento. Elige esta computadora portátil HP y disfruta una solución funcional que equilibra memoria, almacenamiento y comodidad para tus actividades diarias.',899.01,19,N'/images/hp.jpg',3,0),
	 (N'Laptop Acer AG1572P94Q4 Core i9 13900H 16 GB RAM 512 GB SSD 15.6"',N'Lleva tu productividad a un nivel superior con esta Laptop Acer, equipada para quienes buscan mayor potencia al trabajar, estudiar, crear contenido o realizar múltiples actividades desde un mismo equipo. Su procesador Intel Core i9-13900H ofrece un rendimiento avanzado para afrontar tareas exigentes y mantener una experiencia ágil durante jornadas intensivas de uso. Los 16 GB de memoria RAM DDR4 brindan una capacidad multitarea superior, permitiéndote trabajar con diferentes aplicaciones y procesos de forma cómoda, mientras su SSD de 512 GB combina almacenamiento práctico con accesos rápidos a archivos y programas. Su pantalla IPS LCD de 15.6 pulgadas con resolución FHD 1920 x 1080 proporciona un espacio amplio y definido para documentos, contenido multimedia y proyectos profesionales. Además, incorpora Windows 11 Home y gráficos Intel integrados, creando una plataforma versátil para productividad y entretenimiento cotidiano. Su elegante acabado plateado completa un diseño profesional pensado para acompañar un estilo de trabajo moderno y dinámico. ¡Potencia tus proyectos, acelera tu productividad y haz más cada día con el rendimiento de Acer!',1139.01,12,N'/images/axer.jpeg',3,0),
	 (N'Laptop Lenovo 16 GB SSD M.2 512 GB 15.6" Abyss Blue IdeaPad Slim 3',N'La Laptop Lenovo IdeaPad Slim 3 15.6" Abyss Blue combina rendimiento, diseño y practicidad para acompañarte en tus actividades diarias con una experiencia fluida y confiable. Equipada con procesador AMD Ryzen™ 5 5625U Hexa Core, velocidad de hasta 4.3 GHz Max Turbo, 16 GB de memoria RAM DDR4 de 3200 MHz y almacenamiento SSD M.2 de 512 GB, ofrece una respuesta ágil para trabajar, estudiar, crear contenido y organizar tus tareas con mayor eficiencia. Su pantalla IPS de 15.6" FHD con resolución de 1920 x 1080 píxeles y tasa de refresco de 60 Hz brinda una visualización clara para disfrutar documentos, videos, clases o reuniones con buena definición. Integra gráficos AMD Radeon™ compartidos, sistema operativo Windows 11 Home Single Language en español, Wi-Fi, Bluetooth 5.1, puerto HDMI 1.4b, puertos USB 3.2, USB-C con transferencia de datos, Power Delivery y DisplayPort 1.2, lector de tarjetas SD y toma combinada de auriculares y micrófono de 3.5 mm, ofreciendo conectividad útil para el día a día. Sus altavoces orientados al usuario optimizados con Dolby Audio™, micrófonos en matriz y cámara FHD 1080p con obturador de privacidad aportan comodidad para videollamadas y contenido multimedia. Además, cuenta con chip Firmware TPM 2.0, certificación militar MIL-STD-810H, certificación TÜV Rheinland Low Blue Light, batería integrada de 47 Wh, adaptador de corriente de 65 W y diseño liviano de aproximadamente 1.62 kg en color Abyss Blue. Incluye Lenovo 15.6" Laptop Casual Toploader, ideal para llevarla con mayor facilidad. Una laptop pensada para quienes buscan productividad, estilo y confianza en cada jornada.',829.01,31,N'/images/lenovo.jpg',3,0);